### ISSUE TITLE
Optimize Recording notification on Homescreen

### ISSUE THREAD

**Issue by Joostzilla** [jeroenpardon/skin.grid#145]
While recording, on the Homescreen only a small text based notification is (barely)visible.

**Comment by jeroenpardon** [comment]
Sort of a known issue without a proper solution I'm afraid. The skinning engine really needs proper text shadows for things like this. Anything I tried with background colors and such looked horrible :)

**Comment by Joostzilla** [comment]
In the skin for MediaPortal i only used a red dot on every screen of the skin. I feel its more important to know that Kodi is recording than what it is recording. You can always check in Timers.

How about changing the icon in front of LIVE TV on the homescreen into red?
Something like this:
![image](https://user-images.githubusercontent.com/1034920/31888156-3425a6cc-b7fb-11e7-8cad-ad2c64ee6503.png)

**Comment by jeroenpardon** [comment]
Might be worth a shot

**Comment by jeroenpardon** [comment]
Unfortunately I didn't think it through earlier, this can't be done unfortunately. I need something to hook into in order to determine if the list item is a live tv entry. As the home menu is completely configurable (so people can choose whatever label they want on whatever shortcut they want) the label or target of the shortcut are not a reliable variable determine this. This part is solveable though, albeit with some extra coding.

What cannot be changed is that properties like the textcolor, font, etc. have only two states: focused and unfocused. If I set the color based on whichever property of the Live TV shortcut, it will apply to all instances of the icon. Meaning, when I select Live TV *all* icons will turn red.

So this comes down to a skinning engine limitation I'm afraid.

**Comment by jeroenpardon** [comment]
Unfortunately I didn't think it through earlier, this can't be done unfortunately.

I need something to hook into in order to determine if the list item is a live tv entry. As the home menu is completely configurable (so people can choose whatever label they want on whatever shortcut they want) the label or target of the shortcut are not a reliable variable determine this. This part is solveable though, albeit with some extra coding.

What cannot be changed is that properties like the textcolor, font, etc. have only two states: focused and unfocused. If I set the color based on whichever property of the Live TV shortcut, it will apply to all instances of the icon. Meaning, when I select Live TV *all* icons will turn red.

So this comes down to a skinning engine limitation I'm afraid.

**Comment by jeroenpardon** [comment]
Unfortunately I didn't think it through earlier, this can't be done unfortunately.

I need something to hook into in order to determine if the list item is a live tv entry. As the home menu is completely configurable (so people can choose whatever label they want on whatever shortcut they want) the label or target of the shortcut are not a reliable variable determine this. This part is solveable though, albeit with some extra coding.

What cannot be changed is that properties like the textcolor, font, etc. have only two states: focused and unfocused. If I set the color based on whichever property of the Live TV shortcut, it will apply to all instances of the icon. Meaning, when I select Live TV *all* icons will turn red.

So this comes down to a skinning engine limitation I'm afraid.

**Comment by Joostzilla** [comment]
What if you keep the current recording notification as it is but in bold and maybe a red dot in front. Or... The red line you also used in the guide. It could be to the utmost bottom of the screen.

**Comment by jeroenpardon** [comment]
What about this?
![image](https://i.imgur.com/At0DXPR.png)
There will still be instances where it would "fade" when the background is closer to red colours. Nothing at this point I can do about that.

**Comment by Joostzilla** [comment]
I like it. Maybe it could do without 'Currently'.
Maybe you could make the 'recording' icon in the LiveTV pop-up red also.
![image](https://user-images.githubusercontent.com/1034920/31992192-e5e0ace8-b979-11e7-83c4-26839113047e.png)

**Comment by Joostzilla** [comment]
btw. i found a small alignment issue of the timer icon. See image. 
![image](https://user-images.githubusercontent.com/1034920/31992293-31920d44-b97a-11e7-87ee-a7eea944a7ed.png)

**Comment by Joostzilla** [comment]
>There will still be instances where it would "fade" when the background is closer to red colours. Nothing at this point I can do about that.

Is it possible to use a fade from the bottom of the screen just like in the video info screen?

**Comment by jeroenpardon** [comment]
Tried something like that before but it had to be quite dark to actually help in all cases, didn't like it.
Fixed the alignment issue in 5dc087314b5fef1dbb403581a6ba330ba26cadbe, cheers 👍
